[package]
name = "cortado"
version = "0.1.0"
edition = "2021"
default-run = "cortado"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "10.0"
dirs = "4.0"
serde_json = "1.0"
